### PR TITLE
Configurable copy mode for mutable components

### LINKED ISSUE #264: How to handle mutable components?
Currently, mutable components are discouraged, but can be allowed explicitly during world construction. However, there are few fields where we need clarifications:

### StructArray storage

Mutable components are already forbidden with StructArray storage.

With StructArray storage, mutable components are decomposed/composed when added/set and retrieved, respectively. So there is no reference to the original object strored. This may lead to unexpected results.

### Copying entities

When copying entities, mutable components could lead to unexpected results. Currentls (as of #262), only a reference is copied and the component is shared. We could add a kwarg to change this to copy, or even deep copy. Should we use 2 kwargs, an enum, integers, symbols? What shold be the default (I guess shallow copy).

### Documentation

All this should be documented.

### PR DESCRIPTION
**Pull request by mlange-42**
TODO:

- [x] Implement copy modes
- [x] Documentation
- [x] Tests
- [x] Benchmark `copy_entity!`

Fixes #264

### CODE REVIEW

File: src/world.jl [hunk 1]
```diff
@@ -563,14 +564,28 @@ end
 end
 
 """
-    @copy_entity!(world::World, entity::Entity; add::Tuple, remove::Tuple)
+    @copy_entity!(
+        world::World,
+        entity::Entity;
+        add::Tuple=(),
+        remove::Tuple=(),
+        copy=:copy,
```
Comment (Tortar) [inline src/world.jl]:
```suggestion
        mode=:copy,
```

Maybe mode could be better
